language: dart
os:
  - osx
addons:
  chrome: stable
  firefox: latest
jobs:
  include:
    - name: hive
      script:
        - cd hive
        - sh tool/test.sh

    - name: hive chrome
      script:
        - cd hive
        - TEST_PLATFORM = "chrome"
        - sh tool/test.sh

    - name: hive firefox
      script:
        - cd hive
        - TEST_PLATFORM = "firefox"
        - sh tool/test.sh
        
    - name: hive_generator
      script:
        - cd hive_generator
        - pub get
        - pub run test
      
  
    - stage: coverage
      script: sh hive/tool/coverage.sh
