name: basic_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive_flutter:
    path: ../../hive_flutter

  path_provider: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter