name: basic_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive:
    path: ../../hive

  path_provider: any


dev_dependencies:
  flutter_test:
    sdk: flutter