name: drawing_app
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive_flutter: any

  path_provider: ^1.2.0

dev_dependencies:
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true