name: Dart CI

on: [push]

jobs:
  test-hive:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    strategy:
      matrix:
        test-platform: [vm]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        TEST_PLATFORM=${{ matrix.test-platform }}
        sh tool/test_hive.sh

  coverage-hive:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Collect coverage
      run: sh tool/coverage_hive.sh
    - uses: codecov/codecov-action@v1.0.0	
      with:
        token: ${{ secrets.CODECOV_TOKEN }}	
        file: hive/coverage/lcov.info

  build-examples:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        app: [drawing_app, todo_app]
    
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - name: Build app
      run: |
        export PUSH_TOKEN=${{ secrets.PUSH_TOKEN }}
        export APP=${{ matrix.app }}
        sh tool/build_example_for_web.sh

  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update docs
      run: |
        export PUSH_TOKEN=${{ secrets.PUSH_TOKEN }}
        sh tool/update_docs.sh