name: Dart CI

on: [push, pull_request]

jobs:
  test-hive:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    strategy:
      matrix:
        test-platform: [vm]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        export TEST_PLATFORM=${{ matrix.test-platform }}
        sh tool/test_hive.sh
